### ISSUE TITLE
powered and disconnected states correctly recognised, discovering and connected not

### ISSUE THREAD

**Issue by tomradely** [Delgan/yambar-bluetooth#1]
glad this module exists. it's already plenty helpful just to have a click target to power on and off bluetooth.

my issue is that the module does not register when my headphones are connected.

my configuration is as follows:

```
 - script:
        path: /usr/bin/yambar-bluetooth
        content:
          - map:
              conditions:
                powered:
                  - string:
                      on-click: bluetoothctl power off
                      text: "󰂯"
                      deco: {overline: {size: 4, color: ff9e64ff}}
                discovering:
                  - string:
                      text: "󰂰"
                      deco: {overline: {size: 4, color: ff9e64ff}}
                connected:
                  - string:
                      on-click: bluetoothctl power off
                      text: "󰂱 {icon} {name}"
                      deco: {overline: {size: 4, color: 9ece6aff}}
                ~connected:
                  - string:
                      on-click: bluetoothctl power on
                      text: "󰂲"
```

**Comment by Delgan** [comment]
Hey @tomradely.

According to [the `map` documentation](https://www.mankier.com/5/yambar-particles#Map):

> Note that conditions are evaluated in the order they appear. **If multiple conditions are true, the first one will be used.**

I think the problem you're facing is that when you're connecting your headphones, bith `powered` and `connected` evaluate to `true`. Since `powered` is listed first in your configuration, the particle mapped to the `connected` condition never get a chance to be rendered.

You should probably use `&&` conditions or use nested `map`.

**Comment by tomradely** [comment]
Thanks @Delgan! You were exactly right.  for future reference for others, my working setup is as follows:

```
    - script:
        path: /usr/bin/yambar-bluetooth
        content:
          - map:
              conditions:
                ~powered:
                  - string:
                      on-click: bluetoothctl power on
                      text: "󰂲"
                powered && connected:
                  - string:
                      on-click: bluetoothctl power off
                      text: "󰂱 {name}"
                      deco: {overline: {size: 4, color: 9ece6aff}}
                powered && discovering:
                  - string:
                      text: "󰂰"
                      deco: {overline: {size: 4, color: ff9e64ff}}
                ~connected:
                  - string:
                      on-click: bluetoothctl power off
                      text: "󰂯"
                      deco: {overline: {size: 4, color: ff9e64ff}}
```
